// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Platform.Kernel.Persistence;

#nullable disable

namespace Platform.Kernel.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260926200202_AddOutboxDispatching")]
    partial class AddOutboxDispatching
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.Kernel.Outbox.OutboxHandlerReceipt", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("MessageId", "Handler")
                        .HasName("pk_outbox_handler_receipts");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_handler_receipts_tenant_id");

                    b.ToTable("outbox_handler_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenant_id_not_empty", "tenant_id <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("Platform.Kernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND failed_at IS NULL");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenant_id_not_empty", "tenant_id <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("Platform.Kernel.Tenancy.Catalog.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Platform.Kernel.Tenancy.Catalog.TenantDomain", b =>
                {
                    b.Property<string>("Host")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("host");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Host")
                        .HasName("pk_tenant_domains");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_domains_tenant_id");

                    b.ToTable("tenant_domains", (string)null);
                });

            modelBuilder.Entity("Platform.Kernel.Outbox.OutboxHandlerReceipt", b =>
                {
                    b.HasOne("Platform.Kernel.Outbox.OutboxMessage", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_outbox_handler_receipts_outbox_messages_message_id");
                });

            modelBuilder.Entity("Platform.Kernel.Tenancy.Catalog.TenantDomain", b =>
                {
                    b.HasOne("Platform.Kernel.Tenancy.Catalog.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_domains_tenants_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
